[project]
name = 'liquidity-locker'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1'

[[project.requirements]]
contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-amm-swap-pool-v1-1'

[contracts.locker]
path = 'contracts/locker.clar'
depends_on = [ "trait-ownable", "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.vault]
path = 'contracts/vault.clar'
depends_on = [ "trait-semi-fungible", "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

# Test contracts
[contracts.amm-swap-pool-v1-1]
path = 'contracts/test-contracts/amm-swap-pool-v1-1.clar'
depends_on = [ "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.token-amm-swap-pool-v1-1]
path = 'contracts/test-contracts/token-amm-swap-pool-v1-1.clar'
depends_on = [ "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.alex-vault-v1-1]
path = 'contracts/test-contracts/alex-vault-v1-1.clar'
depends_on = [ "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.goatmeme]
path = 'contracts/test-contracts/token/goatmeme.clar'
depends_on = [ "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.dummy]
path = 'contracts/test-contracts/token/dummy.clar'
depends_on = [ "trait-sip-010" ]
clarity_version = 2
epoch = 2.4

[contracts.trait-ownable]
path = 'contracts/traits/trait-ownable.clar'
depends_on = []

[contracts.trait-semi-fungible]
path = 'contracts/traits/trait-semi-fungible.clar'
depends_on = []

[contracts.trait-sip-010]
path = 'contracts/traits/trait-sip-010.clar'
depends_on = []

[contracts.trait-flash-loan-user]
path = "contracts/test-contracts/traits/trait-flash-loan-user.clar"
depends_on = ["trait-sip-010"]

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
